travis:
  secure:
    BINSTAR_TOKEN: WzuZz6WhK1Ue72tLK9RypI35q3oCT8FenoyxMPhN5heim4Fj/SeTpknuljRJQBLNJ6xQaSW18+sI8s6j4U7YwPIjsWTHBDWleRSZm7HMk42XetORkMcp0S91yiSGbbw9uhTdTHjQn+PoUpiq6/aUG69NN1Afmj4MBEzh5K38B0WVraZMP5m77gIHLHH8LbBcGEGGbr8OIHVcXW4U5YwpMvmd+4I+gQGH3r5f0fFGCt75torYTHL3hmB9dDUdpPdseRT8jI46D9CPG7fqPvQpvXUJm+67lIEfkgjAgPBLNA9eZGOcFT7U+G84cns+Ac/k2Nia3NLb5g0t5RKp0KT26/qMVyqDVVDBL2aumqeqvbMc4Qs45D5Jhgqng7vl0nQrgnTtd5CLsEMu1aM0AXcwWruD5ldRmlGV8k46yILouIs1rMY/nT3boYOOKOJvF7XiQBtHods0h0uc+qGTQhCaT5HQCMfLNKxmFcAFIDCvRR7v5qBp6n8q/IjDJU+TMURKw4CLBVrrJKHYx1LCn8I+ha3fIBPnyMaMczF0fDwy4qchtxKo3bRPkwS7jyOI8UAY03YQloaBtpY+iwBOIV1pJ60d8tIchHS6JXsqx4mw9hp5hf5LXEm7gBI7xXOHW/+hWzH/G2zrsxvOG3yVMAD7/D1cr/Y95x/l5K+g2orKRmw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
